/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-12-03 16:52:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.foodapp.model.CartItem;
import com.foodapp.dao.impl.CartDAOImpl;
import com.foodapp.dao.impl.MenuDAOImpl;
import com.foodapp.model.Menu;
import com.foodapp.model.User;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.foodapp.model.Menu");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.foodapp.dao.impl.CartDAOImpl");
    _jspx_imports_classes.add("com.foodapp.model.User");
    _jspx_imports_classes.add("com.foodapp.model.CartItem");
    _jspx_imports_classes.add("com.foodapp.dao.impl.MenuDAOImpl");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    CartDAOImpl cartDAO = new CartDAOImpl();
    MenuDAOImpl menuDAO = new MenuDAOImpl();

    User user = (User) session.getAttribute("user");
    Integer userId = (user != null) ? user.getUserId() : 0;

    List<CartItem> cartItems = cartDAO.getCartByUser(userId);

    double subtotal = 0;
    for(CartItem item : cartItems){
        subtotal += item.getPrice() * item.getQuantity();
    }
    double tax = subtotal * 0.05;
    double discount = subtotal * 0.1;
    double grandTotal = subtotal + tax - discount;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>FoodHub - Your Cart</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/cart.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Toast -->\r\n");
      out.write("<div id=\"toast\"></div>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <i class=\"fa-solid fa-motorcycle\"></i>\r\n");
      out.write("                <span>FoodHub</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"nav-menu\">\r\n");
      out.write("                <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"home.jsp\">Restaurants</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"nav-actions\">\r\n");
      out.write("                ");
 if(user == null){ 
      out.write("\r\n");
      out.write("                    <button onclick=\"location.href='login.jsp'\" class=\"btn btn-login\">Login</button>\r\n");
      out.write("                    <button onclick=\"location.href='signup.jsp'\" class=\"btn btn-signup\">Sign Up</button>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <span>Welcome, ");
      out.print( user.getUsername() );
      out.write("</span>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <div class=\"cart-icon-wrapper\">\r\n");
      out.write("                    <a href=\"cart.jsp\" title=\"View Cart\">\r\n");
      out.write("                        <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    ");
 if(cartItems.size() > 0) { 
      out.write("\r\n");
      out.write("                        <span class=\"cart-badge\">");
      out.print( cartItems.size() );
      out.write("</span>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"back-link-container\">\r\n");
      out.write("    <a href=\"home.jsp\" class=\"back-link\"><i class=\"fa fa-arrow-left\"></i> Back to Restaurants</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"cart-container\">\r\n");
      out.write("    <h2 class=\"cart-title\">Your Cart</h2>\r\n");
      out.write("\r\n");
      out.write("    ");
 if(cartItems.isEmpty()){ 
      out.write("\r\n");
      out.write("        <p class=\"empty-cart\">Your cart is empty.</p>\r\n");
      out.write("    ");
 } else { 
        for(CartItem item : cartItems){
            Menu menu = menuDAO.getMenuItemById(item.getMenuId());
            String imagePath = (menu != null && menu.getImagePath() != null && !menu.getImagePath().isEmpty()) 
                               ? menu.getImagePath() 
                               : "images/default-food.jpg";
    
      out.write("\r\n");
      out.write("            <div class=\"cart-item\" data-menu-id=\"");
      out.print( item.getMenuId() );
      out.write("\">\r\n");
      out.write("                <div class=\"cart-image\">\r\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() + "/" + imagePath );
      out.write("\" \r\n");
      out.write("                         alt=\"");
      out.print( item.getFoodName() );
      out.write("\" \r\n");
      out.write("                         onerror=\"this.src='");
      out.print( request.getContextPath() );
      out.write("/images/default-food.jpg'\"\r\n");
      out.write("                         style=\"width: 80px; height: 80px; object-fit: cover;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cart-content\">\r\n");
      out.write("                    <div class=\"cart-header\">\r\n");
      out.write("                        <h3>");
      out.print( item.getFoodName() );
      out.write("</h3>\r\n");
      out.write("                        <div class=\"cart-price\" data-price=\"");
      out.print( item.getPrice() );
      out.write('"');
      out.write('>');
      out.write('₹');
      out.print( item.getPrice() );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"quantity-controls\">\r\n");
      out.write("                        <button class=\"qty-btn decrease\">-</button>\r\n");
      out.write("                        <input type=\"number\" class=\"quantity-input\" value=\"");
      out.print( item.getQuantity() );
      out.write("\" min=\"1\" max=\"99\">\r\n");
      out.write("                        <button class=\"qty-btn increase\">+</button>\r\n");
      out.write("                        <button class=\"btn-remove\">Remove</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    ");
 }} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cart-summary\">\r\n");
      out.write("        <h3>Order Summary</h3>\r\n");
      out.write("        <div class=\"summary-row\">Subtotal <span id=\"subtotal\">₹");
      out.print( String.format("%.2f", subtotal) );
      out.write("</span></div>\r\n");
      out.write("        <div class=\"summary-row\">Tax (5%) <span id=\"tax\">₹");
      out.print( String.format("%.2f", tax) );
      out.write("</span></div>\r\n");
      out.write("        <div class=\"summary-row\">Discount (10%) <span id=\"discount\">-₹");
      out.print( String.format("%.2f", discount) );
      out.write("</span></div>\r\n");
      out.write("        <div class=\"summary-row grand-total\">Grand Total <span id=\"grandTotal\">₹");
      out.print( String.format("%.2f", grandTotal) );
      out.write("</span></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"payment-method\">\r\n");
      out.write("            <h4>Select Payment Method:</h4>\r\n");
      out.write("            <label><input type=\"radio\" name=\"payment\" value=\"cash\" checked> Cash on Delivery</label>\r\n");
      out.write("            <label><input type=\"radio\" name=\"payment\" value=\"card\"> Credit/Debit Card</label>\r\n");
      out.write("            <label><input type=\"radio\" name=\"payment\" value=\"upi\"> UPI Payment</label>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"checkout-btn\" onclick=\"confirmOrder()\">Confirm Order</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("<p>© 2025 FoodHub | All Rights Reserved | Made with ❤️ </p></footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Toast function\r\n");
      out.write("function showToast(message) {\r\n");
      out.write("    const toast = document.getElementById(\"toast\");\r\n");
      out.write("    toast.textContent = message;\r\n");
      out.write("    toast.className = \"show\";\r\n");
      out.write("    setTimeout(() => {\r\n");
      out.write("        toast.className = toast.className.replace(\"show\", \"\");\r\n");
      out.write("    }, 3000);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Update totals\r\n");
      out.write("function updateTotals() {\r\n");
      out.write("    let subtotal = 0;\r\n");
      out.write("    document.querySelectorAll('.cart-item').forEach(item => {\r\n");
      out.write("        const qty = parseInt(item.querySelector('.quantity-input').value) || 0;\r\n");
      out.write("        const price = parseFloat(item.querySelector('.cart-price').dataset.price) || 0;\r\n");
      out.write("        subtotal += qty * price;\r\n");
      out.write("    });\r\n");
      out.write("    const tax = subtotal * 0.05;\r\n");
      out.write("    const discount = subtotal * 0.1;\r\n");
      out.write("    const grandTotal = subtotal + tax - discount;\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('subtotal').textContent = '₹' + subtotal.toFixed(2);\r\n");
      out.write("    document.getElementById('tax').textContent = '₹' + tax.toFixed(2);\r\n");
      out.write("    document.getElementById('discount').textContent = '-₹' + discount.toFixed(2);\r\n");
      out.write("    document.getElementById('grandTotal').textContent = '₹' + grandTotal.toFixed(2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Update cart quantity to server\r\n");
      out.write("function updateCartServer(menuId, quantity) {\r\n");
      out.write("    fetch('");
      out.print( request.getContextPath() );
      out.write("/updateCart', {\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        headers: {'Content-Type': 'application/x-www-form-urlencoded'},\r\n");
      out.write("        body: `menuId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&quantity=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`\r\n");
      out.write("    }).catch(err => console.error('Cart update failed:', err));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Confirm Order\r\n");
      out.write("function confirmOrder() {\r\n");
      out.write("    const payment = document.querySelector('input[name=\"payment\"]:checked').value;\r\n");
      out.write("    fetch('");
      out.print( request.getContextPath() );
      out.write("/confirmOrder', {\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        headers: {'Content-Type': 'application/x-www-form-urlencoded'},\r\n");
      out.write("        body: `payment=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`\r\n");
      out.write("    })\r\n");
      out.write("    .then(response => {\r\n");
      out.write("        if(response.ok){\r\n");
      out.write("            showToast(\"Order placed successfully!\");\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("            	setTimeout(() => {\r\n");
      out.write("            	    window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/success.jsp';\r\n");
      out.write("            	}, 1200);\r\n");
      out.write("\r\n");
      out.write("            }, 1200);\r\n");
      out.write("        } else {\r\n");
      out.write("            showToast(\"Order failed. Please try again.\");\r\n");
      out.write("        }\r\n");
      out.write("    }).catch(err => {\r\n");
      out.write("        console.error('Order request failed:', err);\r\n");
      out.write("        showToast(\"Order failed. Please try again.\");\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Quantity and Remove Button Events\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    document.querySelectorAll('.cart-item').forEach(item => {\r\n");
      out.write("        const qtyInput = item.querySelector('.quantity-input');\r\n");
      out.write("        \r\n");
      out.write("        item.querySelector('.increase').addEventListener('click', () => {\r\n");
      out.write("            let currentQty = parseInt(qtyInput.value) || 1;\r\n");
      out.write("            qtyInput.value = currentQty + 1;\r\n");
      out.write("            updateTotals();\r\n");
      out.write("            updateCartServer(item.dataset.menuId, qtyInput.value);\r\n");
      out.write("        });\r\n");
      out.write("        item.querySelector('.decrease').addEventListener('click', () => {\r\n");
      out.write("            let currentQty = parseInt(qtyInput.value) || 1;\r\n");
      out.write("            if(currentQty > 1) {\r\n");
      out.write("                qtyInput.value = currentQty - 1;\r\n");
      out.write("                updateTotals();\r\n");
      out.write("                updateCartServer(item.dataset.menuId, qtyInput.value);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        item.querySelector('.btn-remove').addEventListener('click', () => {\r\n");
      out.write("            updateCartServer(item.dataset.menuId, 0);\r\n");
      out.write("            item.style.opacity = '0.5';\r\n");
      out.write("            setTimeout(() => item.remove(), 300);\r\n");
      out.write("            updateTotals();\r\n");
      out.write("        });\r\n");
      out.write("        qtyInput.addEventListener('change', () => {\r\n");
      out.write("            let qty = parseInt(qtyInput.value) || 1;\r\n");
      out.write("            if(qty < 1) qty = 1;\r\n");
      out.write("            if(qty > 99) qty = 99;\r\n");
      out.write("            qtyInput.value = qty;\r\n");
      out.write("            updateTotals();\r\n");
      out.write("            updateCartServer(item.dataset.menuId, qty);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
