/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-12-02 17:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import com.foodapp.model.User;
import com.foodapp.dao.CartDAO;
import com.foodapp.dao.impl.CartDAOImpl;
import com.foodapp.model.CartItem;
import com.foodapp.model.User;
import com.foodapp.dao.impl.CartDAOImpl;
import com.foodapp.dao.CartDAO;
import com.foodapp.model.CartItem;

public final class cart_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.foodapp.dao.CartDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.foodapp.dao.impl.CartDAOImpl");
    _jspx_imports_classes.add("com.foodapp.model.User");
    _jspx_imports_classes.add("com.foodapp.model.CartItem");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("user");
if(user == null){
    response.sendRedirect("login.jsp?error=Please login first");
    return;
}

String message = "";
CartDAO cartDAO = new CartDAOImpl();

String action = request.getParameter("action");
String menuIdStr = request.getParameter("menuId");
String quantityStr = request.getParameter("quantity");

if(action != null){
    int menuId = 0;
    int quantity = 0;
    try {
        if(menuIdStr != null && !menuIdStr.isEmpty()) menuId = Integer.parseInt(menuIdStr);
        if(quantityStr != null && !quantityStr.isEmpty()) quantity = Integer.parseInt(quantityStr);
    } catch(Exception e) {
        message = "Invalid number format!";
    }

    switch(action){
        case "add":
            if(cartDAO.addOrUpdateCart(user.getUserId(), menuId, quantity)){
                message = "Item added/updated successfully!";
            } else {
                message = "Cart update failed!";
            }
            break;
        case "delete":
            if(cartDAO.removeFromCart(user.getUserId(), menuId)){
                message = "Item removed successfully!";
            } else {
                message = "Remove failed!";
            }
            break;
        case "clear":
            if(cartDAO.clearCartByUserId(user.getUserId())){
                message = "Cart cleared!";
            } else {
                message = "Clear cart failed!";
            }
            break;
        case "viewCount":
            message = "Total items in cart: " + cartDAO.getCartItemCount(user.getUserId());
            break;
        default:
            message = "Unknown action!";
    }
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Cart Test - FoodHub</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>Cart Test Page</h2>\r\n");
      out.write("<p>Logged in as: <b>");
      out.print( user.getUsername() );
      out.write("</b></p>\r\n");
      out.write("<p style=\"color:green;\">");
      out.print( message );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<h3>Add / Update Item</h3>\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("    Menu ID: <input type=\"number\" name=\"menuId\" required>\r\n");
      out.write("    Quantity: <input type=\"number\" name=\"quantity\" required>\r\n");
      out.write("    <button type=\"submit\">Add / Update</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<h3>Remove Item</h3>\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("    Menu ID: <input type=\"number\" name=\"menuId\" required>\r\n");
      out.write("    <button type=\"submit\">Remove</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<h3>Clear Cart</h3>\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"clear\">\r\n");
      out.write("    <button type=\"submit\">Clear Cart</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<h3>View Total Items</h3>\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"viewCount\">\r\n");
      out.write("    <button type=\"submit\">View Count</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<h3>Current Cart</h3>\r\n");
      out.write("<ul>\r\n");

List<CartItem> items = cartDAO.getCartByUser(user.getUserId());
if(items.isEmpty()){

      out.write("\r\n");
      out.write("<li>Cart is empty</li>\r\n");

}else{
    for(CartItem item : items){

      out.write("\r\n");
      out.write("<li>Menu ID: ");
      out.print( item.getMenuId() );
      out.write(" | Quantity: ");
      out.print( item.getQuantity() );
      out.write("</li>\r\n");

    }
}

      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
