/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-12-03 17:06:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.foodapp.model.Menu;
import com.foodapp.model.User;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.foodapp.model.Menu");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.foodapp.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    @SuppressWarnings("unchecked")
    List<Menu> menuList = (List<Menu>) request.getAttribute("menuList");
    User user = (User) session.getAttribute("user");
    Integer userId = (user != null) ? user.getUserId() : null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("        <link rel=\"icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/images/fh.png\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Menu - FoodHub</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Menu CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/menu.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- HEADER -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <i class=\"fa-solid fa-motorcycle scooter-icon\"></i>\r\n");
      out.write("                <span>FoodHub</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"nav-menu\">\r\n");
      out.write("                <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Restaurants</a></li>\r\n");
      out.write("                <li><a href=\"#\">Offers</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"nav-actions\">\r\n");
      out.write("                ");
 if(user == null) { 
      out.write("\r\n");
      out.write("                    <button class=\"btn btn-login\" onclick=\"location.href='login.jsp'\">Login</button>\r\n");
      out.write("                    <button class=\"btn btn-signup\" onclick=\"location.href='signup.jsp'\">Sign Up</button>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <span>Welcome, ");
      out.print( user.getUsername() );
      out.write("</span>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <div class=\"cart-icon-wrapper\">\r\n");
      out.write("                    <a href=\"cart.jsp\">\r\n");
      out.write("                        <i class=\"fas fa-shopping-cart cart-icon\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <span class=\"cart-badge\">");
      out.print( session.getAttribute("cartCount") != null ? session.getAttribute("cartCount") : 0 );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- MENU CONTAINER -->\r\n");
      out.write("<div class=\"container menu-container\">\r\n");
      out.write("    <a href=\"home.jsp\" class=\"back-link\"><i class=\"fa fa-arrow-left\"></i> Back to Restaurants</a>\r\n");
      out.write("    <h1 class=\"menu-title\">Menu</h1>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (menuList != null && !menuList.isEmpty()) { 
      out.write("\r\n");
      out.write("        ");
 for (Menu m : menuList) { 
      out.write("\r\n");
      out.write("        <div class=\"menu-item menu-item-wrapper\">\r\n");
      out.write("            <div class=\"menu-image\">\r\n");
      out.write("                <img src=\"");
      out.print( (m.getImagePath() != null && !m.getImagePath().isEmpty()) 
                            ? m.getImagePath() 
                            : "images/restaurants/" + m.getRestaurantId() + "/" + m.getMenuId() + ".jpg" );
      out.write("\" \r\n");
      out.write("                     alt=\"");
      out.print( m.getItemName() );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-content\">\r\n");
      out.write("                <div class=\"menu-header\">\r\n");
      out.write("                    <h3>");
      out.print( m.getItemName() );
      out.write("</h3>\r\n");
      out.write("                    <span class=\"menu-price\">₹");
      out.print( m.getPrice() );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"menu-description\">");
      out.print( m.getDescription() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"quantity-controls\">\r\n");
      out.write("                    <button type=\"button\" class=\"qty-btn decrease\">-</button>\r\n");
      out.write("                    <input type=\"text\" value=\"0\" class=\"quantity-input-display\" readonly>\r\n");
      out.write("                    <button type=\"button\" class=\"qty-btn increase\">+</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-add\" ");
      out.print( !m.isAvailable() ? "disabled" : "" );
      out.write(">Add to Cart</button>\r\n");
      out.write("                    <button type=\"button\" class=\"qty-btn clear\">Clear</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"hidden\" class=\"menu-id\" value=\"");
      out.print( m.getMenuId() );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("        <p class=\"no-menu-items\">No menu items available.</p>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Toast -->\r\n");
      out.write("<div id=\"toast\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- FOOTER -->\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("            <p>© 2025 FoodHub | All Rights Reserved | Made with ❤️ e</p>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- JS for Cart -->\r\n");
      out.write("<script>\r\n");
      out.write("const isLoggedIn = ");
      out.print( (userId != null) ? "true" : "false" );
      out.write(";\r\n");
      out.write("const contextPath = \"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("function showToast(message){\r\n");
      out.write("    const toast = document.getElementById('toast');\r\n");
      out.write("    toast.textContent = message;\r\n");
      out.write("    toast.classList.add('show');\r\n");
      out.write("    setTimeout(()=>toast.classList.remove('show'),2000);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getMenuId(item){\r\n");
      out.write("    const menuInput = item.querySelector(\".menu-id\");\r\n");
      out.write("    return menuInput ? parseInt(menuInput.value || \"0\") : 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addToCart(menuId, quantity, action){\r\n");
      out.write("    if(!isLoggedIn){ window.location.href=\"login.jsp\"; return; }\r\n");
      out.write("    if(menuId<=0){ showToast(\"Invalid menu item\"); return; }\r\n");
      out.write("    const body=\"action=\"+encodeURIComponent(action)+\"&menuId=\"+encodeURIComponent(menuId)+\"&quantity=\"+encodeURIComponent(quantity);\r\n");
      out.write("    fetch(contextPath+\"/cart\",{\r\n");
      out.write("        method:\"POST\",\r\n");
      out.write("        headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},\r\n");
      out.write("        body:body\r\n");
      out.write("    }).then(res=>res.json()).then(data=>{\r\n");
      out.write("        if(data.status===\"success\"){ showToast(\"Cart updated\"); updateCartBadge(data.count); }\r\n");
      out.write("        else showToast(data.message || \"Failed to update cart\");\r\n");
      out.write("    }).catch(err=>{ console.error(err); showToast(\"Network error\"); });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateCartBadge(count){\r\n");
      out.write("    const badge = document.querySelector(\".cart-badge\");\r\n");
      out.write("    if(badge) badge.textContent = count!==undefined ? count : (parseInt(badge.textContent)||0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('DOMContentLoaded',function(){\r\n");
      out.write("    document.querySelectorAll(\".menu-item-wrapper\").forEach(item=>{\r\n");
      out.write("        const decrease=item.querySelector(\".decrease\");\r\n");
      out.write("        const increase=item.querySelector(\".increase\");\r\n");
      out.write("        const clearBtn=item.querySelector(\".clear\");\r\n");
      out.write("        const addBtn=item.querySelector(\".btn-add\");\r\n");
      out.write("        const input=item.querySelector(\".quantity-input-display\");\r\n");
      out.write("\r\n");
      out.write("        decrease?.addEventListener('click',e=>{e.preventDefault();let val=parseInt(input.value||\"0\"); if(val>0) input.value=val-1;});\r\n");
      out.write("        increase?.addEventListener('click',e=>{e.preventDefault(); let val=parseInt(input.value||\"0\"); input.value=val+1; });\r\n");
      out.write("        clearBtn?.addEventListener('click',e=>{e.preventDefault(); input.value=0; const menuId=getMenuId(item); if(menuId>0) addToCart(menuId,0,\"remove\");});\r\n");
      out.write("        addBtn?.addEventListener('click',e=>{e.preventDefault(); const menuId=getMenuId(item); const qty=parseInt(input.value||\"0\"); if(qty>0) addToCart(menuId,qty,\"add\"); else addToCart(menuId,0,\"remove\");});\r\n");
      out.write("    });\r\n");
      out.write("    updateCartBadge();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
