/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-12-03 16:49:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.foodapp.dao.impl.OrderDAOImpl;
import com.foodapp.model.Order;
import com.foodapp.model.User;

public final class trackorder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.foodapp.dao.impl.OrderDAOImpl");
    _jspx_imports_classes.add("com.foodapp.model.Order");
    _jspx_imports_classes.add("com.foodapp.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");

    Order order = null;
    String orderParam = request.getParameter("orderId");
    OrderDAOImpl orderDAO = new OrderDAOImpl();

    if (orderParam != null) {
        try {
            int orderId = Integer.parseInt(orderParam);
            order = orderDAO.getOrderById(orderId);
        } catch (NumberFormatException e) {
            order = null;
        }
    } else if (user != null) {
        order = orderDAO.getLastOrderByUserId(user.getUserId());
    }

    // Determine status color
    String statusColor = "black";
    if(order != null){
        switch(order.getStatus().toLowerCase()){
            case "pending": statusColor = "orange"; break;
            case "completed": statusColor = "green"; break;
            case "cancelled": statusColor = "red"; break;
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Track Order - FoodHub</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/menu.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .order-container { background:#fff; padding:20px; margin:30px auto; border-radius:12px; box-shadow:0 2px 8px rgba(0,0,0,0.1); width:90%; max-width:600px;}\r\n");
      out.write("        .order-row { display:flex; justify-content:space-between; margin:10px 0; font-size:1rem;}\r\n");
      out.write("        .btn-back { margin-top:20px; padding:10px 18px; background:#ff4757; color:white; border:none; border-radius:5px; cursor:pointer; font-weight:bold; transition:background 0.3s; }\r\n");
      out.write("        .btn-back:hover { background:#ff6b81; }\r\n");
      out.write("        #toast { visibility:hidden; min-width:180px; max-width:300px; background-color:#2ed573; color:white; text-align:center; border-radius:8px; padding:12px 16px; position:fixed; z-index:9999; top:20px; right:20px; font-size:14px; opacity:0; transition: opacity 0.3s, visibility 0.3s; box-shadow:0 2px 6px rgba(0,0,0,0.2);}\r\n");
      out.write("        #toast.show { visibility:visible; opacity:1; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- HEADER -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <i class=\"fa-solid fa-motorcycle scooter-icon\"></i>\r\n");
      out.write("                <span>FoodHub</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"nav-menu\">\r\n");
      out.write("                <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Restaurants</a></li>\r\n");
      out.write("                <li><a href=\"#\">Offers</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"nav-actions\">\r\n");
      out.write("                ");
 if(user == null) { 
      out.write("\r\n");
      out.write("                    <button class=\"btn btn-login\" onclick=\"location.href='login.jsp'\">Login</button>\r\n");
      out.write("                    <button class=\"btn btn-signup\" onclick=\"location.href='signup.jsp'\">Sign Up</button>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <span>Welcome, ");
      out.print( user.getUsername() );
      out.write("</span>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <div class=\"cart-icon-wrapper\">\r\n");
      out.write("                    <a href=\"cart.jsp\">\r\n");
      out.write("                        <i class=\"fas fa-shopping-cart cart-icon\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <span class=\"cart-badge\">");
      out.print( session.getAttribute("cartCount") != null ? session.getAttribute("cartCount") : 0 );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Toast -->\r\n");
      out.write("<div id=\"toast\"></div>\r\n");
      out.write("\r\n");
      out.write("<h1 style=\"text-align:center; color:#ff4757; margin-top:30px;\">Track Your Order</h1>\r\n");
      out.write("\r\n");
      out.write("<div class=\"order-container\">\r\n");
 if(order != null) { 
      out.write("\r\n");
      out.write("    <div class=\"order-row\"><span>Order ID:</span><span>");
      out.print( order.getOrderId() );
      out.write("</span></div>\r\n");
      out.write("    <div class=\"order-row\"><span>Restaurant ID:</span><span>");
      out.print( order.getRestaurantId() );
      out.write("</span></div>\r\n");
      out.write("    <div class=\"order-row\"><span>Order Date:</span><span>");
      out.print( order.getOrderDate() );
      out.write("</span></div>\r\n");
      out.write("    <div class=\"order-row\"><span>Total Amount:</span><span>₹");
      out.print( String.format("%.2f", order.getTotalAmount()) );
      out.write("</span></div>\r\n");
      out.write("    <div class=\"order-row\"><span>Payment Mode:</span><span>");
      out.print( order.getPaymentMode() );
      out.write("</span></div>\r\n");
      out.write("    <div class=\"order-row\"><span>Status:</span><span style=\"color:");
      out.print( statusColor );
      out.write("; font-weight:bold;\">");
      out.print( order.getStatus() );
      out.write("</span></div>\r\n");
      out.write("\r\n");
      out.write("    <button class=\"btn-back\" onclick=\"window.location.href='home.jsp'\">Back to Home</button>\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <p style=\"text-align:center; color:red;\">Order not found!</p>\r\n");
      out.write("    <button class=\"btn-back\" onclick=\"window.location.href='home.jsp'\">Go Home</button>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- FOOTER -->\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <p>© 2025 FoodHub | All Rights Reserved | Made with ❤️ e</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
 if(order != null){ 
      out.write("\r\n");
      out.write("    const toast = document.getElementById('toast');\r\n");
      out.write("    toast.innerText = \"Tracking Order #");
      out.print( order.getOrderId() );
      out.write("\";\r\n");
      out.write("    toast.className = 'show';\r\n");
      out.write("    setTimeout(() => { toast.className = toast.className.replace('show',''); }, 3000);\r\n");
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
