/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-12-02 08:49:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.foodapp.model.CartItem;

public final class viewCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.foodapp.model.CartItem");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<CartItem> cartList = (List<CartItem>) request.getAttribute("cartList");
    int userId = 1; // Replace with session userId later

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>My Cart - FoodHub</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body { \r\n");
      out.write("            margin: 0; \r\n");
      out.write("            font-family: 'Segoe UI', sans-serif; \r\n");
      out.write("            background: #f8f9fa; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            background: #ff4757;\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 25px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-item img {\r\n");
      out.write("            width: 110px;\r\n");
      out.write("            height: 90px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-details { flex: 1; }\r\n");
      out.write("\r\n");
      out.write("        .item-details h3 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price {\r\n");
      out.write("            color: #ff4757;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-top: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .qty-controls {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .qty-btn {\r\n");
      out.write("            padding: 6px 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: #ff4757;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .qty-input {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 6px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background: #f7f7f7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remove-btn {\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: red;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-summary {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-top: 25px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .summary-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .checkout-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: #ff4757;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 14px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .clear-cart-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .empty-cart {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            color: #777;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Your Cart</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    ");
 if (cartList == null || cartList.isEmpty()) { 
      out.write("\r\n");
      out.write("        <p class=\"empty-cart\">Your cart is empty 😔</p>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 
            double totalAmount = 0; 
            for (CartItem item : cartList) { 
                totalAmount += item.getPrice() * item.getQuantity();
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cart-item\" data-cart-id=\"");
      out.print( item.getCartId() );
      out.write("\" data-user-id=\"");
      out.print( userId );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"");
      out.print( item.getFoodImage() );
      out.write("\" alt=\"");
      out.print( item.getFoodName() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"item-details\">\r\n");
      out.write("                <h3>");
      out.print( item.getFoodName() );
      out.write("</h3>\r\n");
      out.write("                <p class=\"price\">₹");
      out.print( item.getPrice() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"qty-controls\">\r\n");
      out.write("                <button class=\"qty-btn decrease\">−</button>\r\n");
      out.write("                <input class=\"qty-input\" value=\"");
      out.print( item.getQuantity() );
      out.write("\" readonly>\r\n");
      out.write("                <button class=\"qty-btn increase\">+</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"remove-btn\"><i class=\"fa fa-trash\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Summary -->\r\n");
      out.write("        <div class=\"cart-summary\">\r\n");
      out.write("            <div class=\"summary-row\">\r\n");
      out.write("                <span>Total Amount</span>\r\n");
      out.write("                <span>₹ ");
      out.print( totalAmount );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"checkout-btn\">Proceed to Checkout</button>\r\n");
      out.write("            <button class=\"clear-cart-btn\" id=\"clearCart\">Clear Entire Cart</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Quantity Update / Remove / Clear Cart\r\n");
      out.write("    document.querySelectorAll(\".cart-item\").forEach(item => {\r\n");
      out.write("        let cartId = item.dataset.cartId;\r\n");
      out.write("        let userId = item.dataset.userId;\r\n");
      out.write("        let input = item.querySelector(\".qty-input\");\r\n");
      out.write("\r\n");
      out.write("        // Increase\r\n");
      out.write("        item.querySelector(\".increase\").onclick = () => {\r\n");
      out.write("            let qty = parseInt(input.value) + 1;\r\n");
      out.write("            input.value = qty;\r\n");
      out.write("            updateCart(cartId, qty);\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Decrease\r\n");
      out.write("        item.querySelector(\".decrease\").onclick = () => {\r\n");
      out.write("            let qty = parseInt(input.value);\r\n");
      out.write("            if (qty > 1) {\r\n");
      out.write("                qty--;\r\n");
      out.write("                input.value = qty;\r\n");
      out.write("                updateCart(cartId, qty);\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Delete Item\r\n");
      out.write("        item.querySelector(\".remove-btn\").onclick = () => {\r\n");
      out.write("            deleteItem(cartId, userId);\r\n");
      out.write("        };\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Update cart quantity\r\n");
      out.write("    function updateCart(cartId, qty) {\r\n");
      out.write("        fetch(`cart?action=update&cartId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&quantity=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qty}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, { method: \"POST\" });\r\n");
      out.write("        setTimeout(() => location.reload(), 300);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Delete cart item\r\n");
      out.write("    function deleteItem(cartId, userId) {\r\n");
      out.write("        fetch(`cart?action=delete&cartId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, { method: \"POST\" });\r\n");
      out.write("        setTimeout(() => location.reload(), 300);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Clear entire cart\r\n");
      out.write("    document.getElementById(\"clearCart\")?.addEventListener(\"click\", () => {\r\n");
      out.write("        fetch(`cart?action=clear&userId=");
      out.print( userId );
      out.write("`);\r\n");
      out.write("        setTimeout(() => location.reload(), 300);\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
